### ISSUE TITLE
invalid coin denomination

### ISSUE THREAD

**Issue by jjhesk** [cosmos/testnets#186]
There is an error from invalid coin denomination from staking https://github.com/cosmos/cosmos-sdk/issues/6559

I have looked thru error but I have no clue where to start for looking thru this.

`panic: invalid coin denomination: failed to execute message; message index: 0`

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/genutil.DeliverGenTxs(0x543fca0, 0xc000132008, 0x5457060, 0xc000726ac0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/hesk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.5-rc1/x/genutil/gentx.go:102 +0x30d
github.com/cosmos/cosmos-sdk/x/genutil.InitGenesis(...)
	/Users/hesk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.5-rc1/x/genutil/genesis.go:19
github.com/cosmos/cosmos-sdk/x/genutil.AppModule.InitGenesis(0x543a7e0, 0xc000257260, 0x541d1a0, 0xc0001413b0, 0xc0002a7bd0, 0x543fca0, 0xc000132008, 0x5457060, 0xc000726ac0, 0x0, ...)
	/Users/hesk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.5-rc1/x/genutil/module.go:88 +0x16a
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc0002575e0, 0x543fca0, 0xc000132008, 0x5457060, 0xc000726ac0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/hesk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.5-rc1/types/module/module.go:265 +0x278
github.com/tokenchain/ixo-blockchain/app.(*DpApp).InitChainer(0xc000236d00, 0x543fca0, 0xc000132008, 0x5457060, 0xc000726ac0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/hesk/Documents/ixo/dp-hub/app/app.go:387 +0x11d
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000f5bcc0, 0x3699d820, 0xed68f600f, 0x0, 0xc000045960, 0xb, 0xc000726840, 0x5e8ce68, 0x0, 0x0, ...)
	/Users/hesk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.5-rc1/baseapp/abci.go:39 +0x2cd
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc0010fe960, 0x3699d820, 0xed68f600f, 0x0, 0xc000045960, 0xb, 0xc000726840, 0x5e8ce68, 0x0, 0x0, ...)
	/Users/hesk/go/pkg/mod/github.com/tendermint/tendermint@v0.33.5/abci/client/local_client.go:223 +0xf8
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc0001cf3b0, 0x3699d820, 0xed68f600f, 0x0, 0xc000045960, 0xb, 0xc000726840, 0x5e8ce68, 0x0, 0x0, ...)
	/Users/hesk/go/pkg/mod/github.com/tendermint/tendermint@v0.33.5/proxy/app_conn.go:65 +0x6b
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000fa30a0, 0xa, 0x0, 0xc000045f76, 0x6, 0xc000045fa0, 0xb, 0x0, 0x0, 0x0, ...)
	/Users/hesk/go/pkg/mod/github.com/tendermint/tendermint@v0.33.5/consensus/replay.go:319 +0x69b
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000fa30a0, 0x545a7e0, 0xc000181400, 0x80, 0x4e734c0)
	/Users/hesk/go/pkg/mod/github.com/tendermint/tendermint@v0.33.5/consensus/replay.go:269 +0x485
github.com/tendermint/tendermint/node.doHandshake(0x5459b60, 0xc000010240, 0xa, 0x0, 0xc000045f76, 0x6, 0xc000045fa0, 0xb, 0x0, 0x0, ...)
	/Users/hesk/go/pkg/mod/github.com/tendermint/tendermint@v0.33.5/node/node.go:264 +0x19a
github.com/tendermint/tendermint/node.NewNode(0xc000f5b2c0, 0x5438ee0, 0xc000f3a6e0, 0xc000f32250, 0x541b920, 0xc000fba9e0, 0xc000f324e0, 0x51c9558, 0xc000f324f0, 0x54406e0, ...)
	/Users/hesk/go/pkg/mod/github.com/tendermint/tendermint@v0.33.5/node/node.go:587 +0x343
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000f64220, 0x51cacd8, 0x1d, 0x0, 0x0)
	/Users/hesk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.5-rc1/server/start.go:177 +0x4b0
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000f78840, 0xc000f646c0, 0x0, 0x2, 0x0, 0x0)
	/Users/hesk/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.5-rc1/server/start.go:81 +0xb4
github.com/spf13/cobra.(*Command).execute(0xc000f78840, 0xc000f646a0, 0x2, 0x2, 0xc000f78840, 0xc000f646a0)
	/Users/hesk/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc00014db80, 0x2, 0xc000f645a0, 0x5060159)
	/Users/hesk/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/hesk/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc00014db80, 0x51cb128, 0x3, 0xc000f27070)
	/Users/hesk/go/pkg/mod/github.com/tendermint/tendermint@v0.33.5/libs/cli/setup.go:89 +0x3c
main.main()
	/Users/hesk/Documents/ixo/dp-hub/cmd/dpd/main.go:70 +0x68c

```json
{
  "genesis_time": "2020-07-02T04:56:47.916052Z",
  "chain_id": "ddp-1x",
  "consensus_params": {
    "block": {
      "max_bytes": "22020096",
      "max_gas": "-1",
      "time_iota_ms": "1000"
    },
    "evidence": {
      "max_age_num_blocks": "100000",
      "max_age_duration": "172800000000000"
    },
    "validator": {
      "pub_key_types": [
        "ed25519"
      ]
    }
  },
  "app_hash": "",
  "app_state": {
    "auth": {
      "params": {
        "max_memo_characters": "256",
        "tx_sig_limit": "7",
        "tx_size_cost_per_byte": "10",
        "sig_verify_cost_ed25519": "590",
        "sig_verify_cost_secp256k1": "1000"
      },
      "accounts": [
        {
          "type": "cosmos-sdk/Account",
          "value": {
            "address": "dx01l2ktgqpgj4d4nq0m2fcdgx7kphvgqs2zudf3cp",
            "coins": [
              {
                "denom": "dap",
                "amount": "10000000000"
              },
              {
                "denom": "dollar",
                "amount": "10000000"
              },
              {
                "denom": "stake",
                "amount": "100000000"
              }
            ],
            "public_key": "",
            "account_number": 0,
            "sequence": 0
          }
        },
        {
          "type": "cosmos-sdk/Account",
          "value": {
            "address": "dx019qyhfy6ns3mtzpaxwxmzx0y2xz0pt2l0zvqp8f",
            "coins": [
              {
                "denom": "dap",
                "amount": "100"
              },
              {
                "denom": "dollar",
                "amount": "10000"
              },
              {
                "denom": "stake",
                "amount": "100000000"
              }
            ],
            "public_key": "",
            "account_number": 0,
            "sequence": 0
          }
        },
        {
          "type": "cosmos-sdk/Account",
          "value": {
            "address": "dx01a7c9mdqpnq5p27c4cw94u3g4s5nl5cwffkdxsu",
            "coins": [
              {
                "denom": "dap",
                "amount": "100"
              },
              {
                "denom": "dollar",
                "amount": "10000"
              },
              {
                "denom": "stake",
                "amount": "100000000"
              }
            ],
            "public_key": "",
            "account_number": 0,
            "sequence": 0
          }
        },
        {
          "type": "cosmos-sdk/Account",
          "value": {
            "address": "dx01jppmr9l66hl83x3rret8jntmchavvcljten63z",
            "coins": [
              {
                "denom": "dap",
                "amount": "10000000"
              },
              {
                "denom": "dollar",
                "amount": "10000"
              },
              {
                "denom": "stake",
                "amount": "100000000"
              }
            ],
            "public_key": "",
            "account_number": 0,
            "sequence": 0
          }
        }
      ]
    },
    "gov": {
      "starting_proposal_id": "1",
      "deposits": null,
      "votes": null,
      "proposals": null,
      "deposit_params": {
        "min_deposit": [
          {
            "denom": "stake",
            "amount": "10000000"
          }
        ],
        "max_deposit_period": "172800000000000"
      },
      "voting_params": {
        "voting_period": "172800000000000"
      },
      "tally_params": {
        "quorum": "0.334000000000000000",
        "threshold": "0.500000000000000000",
        "veto": "0.334000000000000000"
      }
    },
    "project": {
      "project_docs": null,
      "account_maps": null,
      "withdrawal_infos": null,
      "params": {
        "dp_did": "did:dxp:PGtRP4o5cCYhe8B5Fu7xj6",
        "project_minimum_initial_funding": "1"
      }
    },
    "did": {
      "did_docs": null
    },
    "oracles": {
      "oracles": [
        {
          "oracle_did": "did:dxp:XX1rB7o9BeEmNuvB5PeAn2",
          "capabilities": [
            {
              "denom": "dap",
              "capabilities": [
                "mint"
              ]
            }
          ]
        },
        {
          "oracle_did": "did:dxp:Xc7PR8S7A6AzreYR5th2h4",
          "capabilities": [
            {
              "denom": "dap",
              "capabilities": [
                "mint",
                "burn",
                "transfer"
              ]
            }
          ]
        },
        {
          "oracle_did": "did:dxp:QmuNtGJCJZuU8wm8e9PSWk",
          "capabilities": [
            {
              "denom": "dollar",
              "capabilities": [
                "transfer"
              ]
            },
            {
              "denom": "dap",
              "capabilities": [
                "transfer"
              ]
            }
          ]
        },
        {
          "oracle_did": "did:dxp:PQQMd4iP8XUpctiETKRhW2",
          "capabilities": [
            {
              "denom": "dollar",
              "capabilities": [
                "transfer",
                "burn",
                "mint"
              ]
            }
          ]
        }
      ]
    },
    "slashing": {
      "params": {
        "signed_blocks_window": "100",
        "min_signed_per_window": "0.500000000000000000",
        "downtime_jail_duration": "600000000000",
        "slash_fraction_double_sign": "0.050000000000000000",
        "slash_fraction_downtime": "0.010000000000000000"
      },
      "signing_infos": {},
      "missed_blocks": {}
    },
    "staking": {
      "params": {
        "unbonding_time": "1814400000000000",
        "max_validators": 100,
        "max_entries": 7,
        "historical_entries": 0,
        "bond_denom": "stake"
      },
      "last_total_power": "0",
      "last_validator_powers": null,
      "validators": null,
      "delegations": null,
      "unbonding_delegations": null,
      "redelegations": null,
      "exported": false
    },
    "params": null,
    "treasury": null,
    "upgrade": {},
    "crisis": {
      "constant_fee": {
        "denom": "stake",
        "amount": "1000"
      }
    },
    "mint": {
      "minter": {
        "inflation": "0.130000000000000000",
        "annual_provisions": "0.000000000000000000"
      },
      "params": {
        "mint_denom": "stake",
        "inflation_rate_change": "0.130000000000000000",
        "inflation_max": "0.200000000000000000",
        "inflation_min": "0.070000000000000000",
        "goal_bonded": "0.670000000000000000",
        "blocks_per_year": "6311520"
      }
    },
    "evidence": {
      "params": {
        "max_evidence_age": "120000000000"
      },
      "evidence": []
    },
    "nameservice": {
      "whois_records": []
    },
    "genutil": {
      "gentxs": [
        {
          "type": "cosmos-sdk/StdTx",
          "value": {
            "msg": [
              {
                "type": "cosmos-sdk/MsgCreateValidator",
                "value": {
                  "description": {
                    "moniker": "dphomeworld",
                    "identity": "",
                    "website": "",
                    "security_contact": "",
                    "details": ""
                  },
                  "commission": {
                    "rate": "0.100000000000000000",
                    "max_rate": "0.100000000000000000",
                    "max_change_rate": "0.100000000000000000"
                  },
                  "min_self_delegation": "1",
                  "delegator_address": "dx01l2ktgqpgj4d4nq0m2fcdgx7kphvgqs2zudf3cp",
                  "validator_address": "dx0valoper1l2ktgqpgj4d4nq0m2fcdgx7kphvgqs2zstn6ap",
                  "pubkey": "dx0valconspub1zcjduepq28yh79fasqs4cuznz28tl9f0wluqd9ke8cchgqnwyztczqghravqwdff8v",
                  "value": {
                    "denom": "dap",
                    "amount": "10000"
                  }
                }
              }
            ],
            "fee": {
              "amount": [],
              "gas": "200000"
            },
            "signatures": [
              {
                "pub_key": {
                  "type": "tendermint/PubKeySecp256k1",
                  "value": "A719u7lf5sPXLfWDIChWhcqIJ5BLaTmwy+FMdcU+ok8o"
                },
                "signature": "A4MdfCOHTcr5BHNSrOFPMYbsRNrlXVubOLWrbZnxkPJewN8/7aGaurVLtliRtkKBWgSCeQNZrO2Tep2pz3Bjow=="
              }
            ],
            "memo": "3155140d5e45a746ab5eea952a3d3c0576b27087@192.168.1.2:26656"
          }
        }
      ]
    },
    "bonds": {
      "bonds": null,
      "batches": null
    },
    "bonddoc": {
      "bond_docs": null
    },
    "distribution": {
      "params": {
        "community_tax": "0.020000000000000000",
        "base_proposer_reward": "0.010000000000000000",
        "bonus_proposer_reward": "0.040000000000000000",
        "withdraw_addr_enabled": true
      },
      "fee_pool": {
        "community_pool": []
      },
      "delegator_withdraw_infos": [],
      "previous_proposer": "",
      "outstanding_rewards": [],
      "validator_accumulated_commissions": [],
      "validator_historical_rewards": [],
      "validator_current_rewards": [],
      "delegator_starting_infos": [],
      "validator_slash_events": []
    },
    "bank": {
      "send_enabled": true
    },
    "payments": {
      "params": {
        "ixo_factor": "1.000000000000000000",
        "initiation_fee_amount": "500000.000000000000000000",
        "initiation_node_fee_percentage": "0.000000000000000000",
        "claim_fee_amount": "600.000000000000000000",
        "evaluation_fee_amount": "400.000000000000000000",
        "service_agent_registration_fee_amount": "0.000000000000000000",
        "evaluation_agent_registration_fee_amount": "0.000000000000000000",
        "node_fee_percentage": "0.500000000000000000",
        "evaluation_pay_fee_percentage": "0.100000000000000000",
        "evaluation_pay_node_fee_percentage": "0.400000000000000000"
      },
      "payment_templates": null,
      "payment_contracts": null,
      "subscriptions": null
    },
    "supply": {
      "supply": []
    }
  }
}
```

**Comment by marbar3778** [comment]
Are you trying to start a new testnet? also here you must alter the denomination: 

```
      "params": {
        "unbonding_time": "1814400000000000",
        "max_validators": 100,
        "max_entries": 7,
        "historical_entries": 0,
        "bond_denom": "stake"
      },
```

**Comment by jjhesk** [comment]
@marbar3778 does need to keep using stake?

**Comment by marbar3778** [comment]
if you would like you can, but then your create validator cmd should be with stake. Multi denomination staking is not implemented.

**Comment by jjhesk** [comment]
I would like to use "dap" for staking.. can I do so? 
https://jqplay.org/s/aF3tPhatgy

**Comment by marbar3778** [comment]
yes you must replace the bond_denom in genesis. You can search for stake and replace it with dap.
